import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../shell/home_shell.dart';
import 'theme.dart';

/// Root widget of Clockwork.
///
/// This widget is intentionally tiny: it picks the theme, sets up
/// `MaterialApp`, and delegates the actual UI to [HomeShell]. Anything
/// that touches platform plugins or Riverpod state lives in [HomeShell]
/// (or further down the tree).
class ClockworkApp extends ConsumerWidget {
  const ClockworkApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      title: 'Clockwork',
      theme: buildLightTheme(),
      darkTheme: buildDarkTheme(),
      localizationsDelegates: const [
        // Generated by `flutter gen-l10n` once `flutter pub get` is run.
        // Until then the empty list is fine — Flutter will fall back to
        // the English-only Material delegates registered below.
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale('en')],
      home: const HomeShell(),
    );
  }
}
